### ISSUE TITLE
Error on database when trying to add a ChooseGroup resource

### ISSUE THREAD

**Issue by nahuelsgk** [IOC/moodle-mod_choosegroup#1]
In a fresh installation of moodle, the next exception is raised:

Debug info: ERROR: invalid input syntax for integer: ""
SELECT id, groupid, maxlimit FROM mdl_choosegroup_group WHERE choosegroupid = $1 ORDER BY groupid
[array (
0 => '',
)]
Error code: dmlreadexception
Stack trace:

```
line 426 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 753 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1211 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1162 of /lib/dml/moodle_database.php: call to moodle_database->get_records_select()
line 98 of /mod/choosegroup/mod_form.php: call to moodle_database->get_records()
line 401 of /course/moodleform_mod.php: call to mod_choosegroup_mod_form->data_preprocessing()
line 262 of /course/modedit.php: call to moodleform_mod->set_data()
```

The param passed to the query is empty.

**Comment by reskit** [comment]
Sorry for not resolve this ticket earlier, today I realized there was a ticket waiting to be resolved. 

Someone else have created the same issue and now it's resolved.

My apologies for resolving it too late
