### ISSUE TITLE
Do not depend on chat language strings

### ISSUE THREAD

**Issue by crazyserver** [IOC/moodle-mod_choosegroup#2]
I have realised that this module depends on chat module strings. I think that it just uses one: chatintro on on mod_form.php.

You can find more information about this problem on https://tracker.moodle.org/browse/MDL-47875

Cheers!

**Comment by reskit** [comment]
Hi crazyserver,

I've changed the only reference to chat language string for 'description' moodle common string

Thanks for your feedback!
